function Body() {
    return (
    <div className="bg-secondary-color">
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
        @<br/>
    </div>
    )
}

export default Body;